name: Sync Frontend
on:
  push:
    branches: [main]
jobs:
  sync:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v4
      with:
        ref: main
        fetch-depth: 0  

    - name: Setup Git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Sync to frontend branch
      run: git fetch --all

    - name: Check if frontend branch exists remotely
      run: |  
        if git show-ref --quiet refs/remotes/origin/frontend; then
          git checkout frontend
          git reset --hard origin/main  # Reset to match main exactly
        else
          git checkout -b frontend
        fi

    - name: Explicitly keep only frontend files
    - run: |
          git checkout main -- \
          app/ \
          components/ \
          lib/supabase.ts \
          hooks/ \
          lib/ \
          next.config.js \
          package.json \
          tsconfig.json \
          next-env.d.ts \
          components.json \
          postcss.config.js \
          tailwind.config.ts \
          tsconfig.json

          git add .
          if ! git diff-index --quiet HEAD --; then
            git commit -m "chore: sync frontend from main [skip ci]"
            git push origin frontend
          else
            echo "No changes to sync"
          fi